import type { Metadata } from 'next'
import { Inter, Lato, Noto_Sans_JP } from 'next/font/google'
import './globals.css'
import { GeolocationProvider } from '@/contexts/GeolocationProvider';


const notoSansJP = Noto_Sans_JP({
  subsets: ['latin'],
  variable: '--font-noto-sans-jp',

})


export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={notoSansJP.className}>
        <GeolocationProvider>
          {children}
        </GeolocationProvider>

      </body>
    </html>
  )
}
